### ISSUE TITLE
review endpoints needed for admin site

### ISSUE THREAD

**Issue by jakemoves** [jakemoves/cohort-server#145]

**Comment by jakemoves** [comment]
@helloCaller I think these are the endpoints needed for your sprint 3 tasks, let me know if I'm missing any... 

- UPDATE `/events/:id/occasions/:id/open` (button)
- UPDATE `/events/:id/occasions/:id/close` (button)
- GET `/events/:id/occasions/:id/qr-code` (button / link) - or we can include the qr code URL in the occasion JSON
- POST `/events/:id/occasions/:id/broadcast` (slider triggers this)
- DELETE `/events/:id/occasions/:id` (button)

**Comment by helloCaller** [comment]
Will we need a delete/remove event?

**Comment by jakemoves** [comment]
Good catch @helloCaller, here's the updated list. I spend today on /broadcast, think it's mostly done, just deploying for testing now. Note that the endpoint URLs have changed from the above, and that `/api/v2` should prefix all endpoint URLs.

done, testing:
- open occasion: PATCH `/occasions/:id` with payload `{ state: 'opened'}` (button)
- close occasion: PATCH `/occasions/:id` with payload `{state: 'closed'}` (button)
- POST `/occasions/:id/broadcast` with a cue (slider triggers this)

not done yet:
- GET /events/:id/occasions/:id/qr-code (button / link) - or we can include the qr code URL in the occasion JSON
- DELETE `/occasions/:id` (button)
- DELETE `/event/:id` (not sure where in the UI this is called from

**Comment by jakemoves** [comment]
Ok, I've added delete endpoints for occasions and events. It's easy to get the local data or UI state de-synched from the server when doing these operations, so let's talk over our approach on a call @helloCaller .

I'm breaking the QR code into a new issue, so closing this one.
