### ISSUE TITLE
Would it be better to have links to outside websites pop up in a new window/tab? links that lead to internal material can stay in the same tab - same for the github, open a new tab?

### ISSUE THREAD

**Issue by helloCaller** [jakemoves/cohort-server#148]
hmm, not sure what best practices around this is these days. I personally find new tabs a little more abrasive for navigation back to the initial site. I'm open to discussion about it though, and it's an easy thing to implement.

**Comment by jakemoves** [comment]
Let’s stick with default behaviour here — links open in same tab.

(One reason to change this might be if the user is on a page of a web app that has a ton of unsaved state)

**Comment by jakemoves** [comment]
@AmandaLBaker , once you've seen this, please close this issue :)
