### ISSUE TITLE
Project website: Production names wrap badly at a certain breakpoint

### ISSUE THREAD

**Issue by jakemoves** [jakemoves/cohort-server#158]
**OS / Browsers**
macOS Safari & Chrome

**Steps to reproduce**
- open the project website on a laptop browser
- make the browser window the full width of the screen
- note the production names look good
- resize the window to just under 1200px 

**Expected result**
- everything looks sensible

**Actual result**
- production names start wrapping funkily

**Notes**
- pretty sure this is related to a particular Bootstrap breakpoint (<1200px)
- ignore the blue-ish overlay in the images

Wider than 1200px
<img alt=">1200px" src="https://user-images.githubusercontent.com/4842862/69768218-f8512980-113c-11ea-8b63-4a2dbf4f5ceb.png">

Narrower than 1200px
<img alt="Screen Shot 2019-11-27 at 5 35 22 PM" src="https://user-images.githubusercontent.com/4842862/69768246-0f901700-113d-11ea-8363-7e6aa1217639.png">

**Comment by helloCaller** [comment]
Fixed the breakpoints, but had to change the layout at that size to this (pictured).
<img width="379" alt="Screen Shot 2019-11-28 at 1 30 03 AM" src="https://user-images.githubusercontent.com/9770973/69782397-e85a3980-117e-11ea-9bbe-e72306715348.png">

**Comment by jakemoves** [comment]
Looks good to me! Can you flip to Amanda to verify & close?

**Comment by AmandaLBaker** [comment]
Looks great!
