### ISSUE TITLE
use real QR codes from server in admin site

### ISSUE THREAD

**Issue by jakemoves** [jakemoves/cohort-server#161]
Okay, QR codes for occasions are ready on the backend.

It comes over the wire as an SVG, so you can just dump it into a DOM element and it should display.

Here's some example code. I think it's fine to request this on demand / when the user wants to see it, it's a tiny request. (If you wanted you could do the request once and store the result, as long as you re-request if the occasion / event changes. I don't know that there's much benefit to that right now though.)

```
let response = await fetch(serverURL + "/occasions/3/qrcode", {
    method: 'GET'
})
let qrcode = await response.text()
let qrContainer = document.getElementById([some container element])
qrContainer.innerHTML = qrcode
```

**Comment by helloCaller** [comment]
Implemented.

**Comment by jakemoves** [comment]
🍻
