### ISSUE TITLE
Favicons for admin site & project site

### ISSUE THREAD

**Issue by jakemoves** [jakemoves/cohort-server#163]
Here are two images for use as favicons (either is fine, just different resolutions)
![iPhone App 60pt@2x](https://user-images.githubusercontent.com/4842862/69835089-29dcfa00-11fc-11ea-9c66-a10f84dcbe7c.png)
![iPhone App 60pt@3x](https://user-images.githubusercontent.com/4842862/69835090-29dcfa00-11fc-11ea-9e22-3bafb3d7c8c0.png)

**Comment by helloCaller** [comment]
I've put this in, but I would strongly recommend getting a graphic designer to come up with a couple of other options.

**Comment by jakemoves** [comment]
Yup. This is very definitely a placeholder.
