### ISSUE TITLE
Implement delete occasion functionality + add delete event functionality

### ISSUE THREAD

**Issue by helloCaller** [jakemoves/cohort-server#171]

**Comment by jakemoves** [comment]
Backend has been updated on sprint-2: it will respond with a 400 error if a to-be-deleted event has open occasions. Trying to delete an open occasion directly should result in the same error.

**Comment by helloCaller** [comment]
Opened a separate issue on updating UI in case of delete errors, but core functionality is there.

**Comment by AmandaLBaker** [comment]
The core functionality of create and delete works, no other details with create as of yet on admin site (such as inputting event information at that stage)
