### ISSUE TITLE
Verify keyboard accessibility on admin site

### ISSUE THREAD

**Issue by jakemoves** [jakemoves/cohort-server#172]
The easiest way / first step to support screenreaders and other a11y tools is to make sure the site is usable with only the keyboard, using tab to highlight fields and buttons and so on. (**big note**: do NOT have Dev Tools / inspector open when testing keyboard accessibility)

Right now only the first two elements on the login page are navigable with the keyboard, which leads me to think the overall borked-ness is because of our show/hide setup. Keep an eye on this as we begin to break down into components and let's see if it gets better.

**Comment by helloCaller** [comment]
Changing to page states rather than dynamically changing display on elements seems to have addressed this.
