### ISSUE TITLE
Open occasions do not display 'back' button

### ISSUE THREAD

**Issue by jakemoves** [jakemoves/cohort-server#176]
*Steps to reproduce*
- open admin site
- view an open occasion

*Expected result*
Back button at top left allows user to return to previous page

*Actual result*
No back button displays. (The back button displays when the event is closed, though.)

<img width="451" alt="Screen Shot 2020-01-18 at 12 51 36 PM" src="https://user-images.githubusercontent.com/4842862/72668122-7faa7300-39f1-11ea-96ff-dfcda39c7ef5.png">

**Comment by helloCaller** [comment]
Yeah, I left it out for now cause I wasn't sure how much we want to necessitate the closing of occasions. I can add it back in easily (thanks components!), if there's no foreseeable issue with open occasions on the server.

**Comment by jakemoves** [comment]
Do you mean because it’s easy to put the UI in an inconsistent state as far as opened/closed?

**Comment by helloCaller** [comment]
Not inconsistent, but if an occasion is left open then it will just remain that way. In terms of UI, if I come back to an open occasion then it skips the "closed" state and goes directly to "open". Which I don't think is a problem. I just imagined (potentially) no one ever closing the occasions.

**Comment by jakemoves** [comment]
Ah. I think we actually want to encourage user to close occasions when they’re finished, as right now it’s the closing of an occasion that signals us to throw out any info we have about devices etc. Also closed occasions don’t take up any server resources, but open ones do.

**Comment by helloCaller** [comment]
ok. When are we considering them finished? At/after the last cue? I can also put a prompt in when they hit "back" asking if they want to close the occasion.

**Comment by jakemoves** [comment]
We consider the occasion finished when the user closes it. If we find real users are never closing their occasions then we can add some prompts etc but for now let’s keep it simple. 

xJ

**Comment by helloCaller** [comment]
I've just added a back button, no other verifying of if occasion is closed.

**Comment by jakemoves** [comment]
Ok, please assign to Amanda when this is testable on staging.

**Comment by AmandaLBaker** [comment]
Back button showing on all desired pages on desktop and mobile
