### ISSUE TITLE
Brief flash of "no events" screen after password is entered

### ISSUE THREAD

**Issue by AmandaLBaker** [jakemoves/cohort-server#180]
When logging into the admin site, there's a brief flash of a "no events" message before the events are populated. The duration of said message varies, most noticeable/longest when accessing from a desktop browser.

_Note from Jacob:_ Suggestion: hold off on rendering the event list until either a success/error is received from the server call, or a short timeout is reached.

**Comment by helloCaller** [comment]
With the refactor of the site, the grabbing of events now happens sooner (before the page is populated, whereas before it was happening in quick succession). This doesn't seem to be an issue in my testing anymore, but let me know if you still see it.

**Comment by jakemoves** [comment]
Please assign back to Amanda when this is testable on staging.

**Comment by AmandaLBaker** [comment]
No longer showing the flash of "no events"
