### ISSUE TITLE
Desktop version of "slider" is cumbersome to call

### ISSUE THREAD

**Issue by AmandaLBaker** [jakemoves/cohort-server#181]
Slider is cumbersome to call on desktop (vs. on mobile). Slider also stretches fairly wide depending on resolution of desktop browser.

**Comment by jakemoves** [comment]
@helloCaller Can we cause the whole admin site to appear in a centred column on desktop (aka use a mobile-ish width on desktop)? Then we can stay focused on mobile and deal with a wider / adjusted desktop layout when we have users asking for it or features that benefit from it.

**Comment by helloCaller** [comment]
Made the global width of the site smaller on devices bigger than a mobile screen. I've checked in chrome on multiple device widths, but this may need to be double checked.

**Comment by AmandaLBaker** [comment]
Checked on multiple browsers and multiple resolutions, and it looks to be good across all of them.
