### ISSUE TITLE
Exiting QR code pop-up redirects back to occasion list

### ISSUE THREAD

**Issue by AmandaLBaker** [jakemoves/cohort-server#182]
Exiting the QR code leads back to the occasion list. Would be more streamlined to return to opened occasion page. Redirection also results in requiring user to reopen the occasion, even through it hasn't been manually exited (only redirected due to pulling up the QR code).

**Comment by jakemoves** [comment]
@AmandaLBaker This is a good description of the issue, but could you please add explicit steps to reproduce and assign back to Luke?

**Comment by AmandaLBaker** [comment]
Steps to reproduce (based on current events & occasions on admin site):

- enter admin site v2
- open "demo event" occasions
- open any of the demo event shows

If chosen demo event is already open (due to error of some being "pre-opened"):
- click "show QR code"
- click on upper right x to close
- user has now been redirected back to "demo event" occasions

If chosen demo event is not open:
- click "open occasion"
- click "show QR code"
- click on upper right x to close
- user has now been redirected back to "demo event" occasions
- if user clicks on the chosen show again, one will see that it must be reopened, yet it was never properly closed in the process of getting the QR code

**Comment by helloCaller** [comment]
Qr code now opens as a modal, so closing it should now simply close the modal (the user never leaves the page).

**Comment by jakemoves** [comment]
Ok, please assign back to Amanda when this fix is testable on staging

**Comment by AmandaLBaker** [comment]
Working as intended with QR opening as a modal on both mobile and desktop admin site. However only internal QR codes actually connect (once an occasion has been opened). Will create a new issue for this.
