### ISSUE TITLE
Create empty pages for Get Started and Downloads

### ISSUE THREAD

**Issue by jakemoves** [jakemoves/cohort-server#230]
/get-started/index.html
/downloads/index.html

**Comment by helloCaller** [comment]
I made separate .html files, like get-started.html and downloads.html, but would you rather them formatted as above?

**Comment by jakemoves** [comment]
Hmm, good question... I’ve more often seen subfolders and index.html files, but if the URLs work your way without needing extensions, I’m fine with that. (I.E. `cohort.rocks/get-started` is what we want, not `cohort.rocks/get-started.html`)

**Comment by helloCaller** [comment]
It is possible, but more work than just making the folders. Just made the folders, and now up on staging.

**Comment by jakemoves** [comment]
These look great. Good work. I like the water bg image :)
