### ISSUE TITLE
Blog: The Rough and Tumble of Tech Part 3 and 4 have missing links 

### ISSUE THREAD

**Issue by helloCaller** [jakemoves/cohort-server#243]
The Rough and Tumble of Tech Part 3 and 4 offer navigation to the other parts in their footers, but aren't actually links.
<img width="304" alt="Screen Shot 2020-10-30 at 10 12 14 PM" src="https://user-images.githubusercontent.com/9770973/97768975-706a6100-1afd-11eb-9740-86055e56d6fd.png">

**Comment by AmandaLBaker** [comment]
Created new issue #258 for links in general on blog. This one has been fixed and addressed further there.
