### ISSUE TITLE
🔴 Blog: Spruce up the Blog archive page

### ISSUE THREAD

**Issue by AmandaLBaker** [jakemoves/cohort-server#257]
- edit the list of links to ensure readability of article title, date, author(s), and appropriate tags
- add brief tagline/description/snippet of each article as you see fit (if wanting more than just tags)

**Comment by jakemoves** [comment]
I've added excerpts and authors, and removed the months (since it doesn't really correspond to anything in reality other than 'order we wanted things to show up').

**Comment by jakemoves** [comment]
I don't think tags are necessarily needed on this listing... let me know if you have strong feelings

**Comment by AmandaLBaker** [comment]
Looks really good! I'm fine not having tags on that page. 

Only note is in all the by-lines on the archive page, "Sebastien Heins" requires é on the first e for: Sébastien Heins. His name otherwise appears correct within the articles.

**Comment by jakemoves** [comment]
Good find, thanks! I've corrected it.

**Comment by AmandaLBaker** [comment]
Awesome! Everything looks good, so going to close
