### ISSUE TITLE
🔵 Blog: Check links throughout Blog that connect out to other sites

### ISSUE THREAD

**Issue by AmandaLBaker** [jakemoves/cohort-server#258]
Do a pass through all articles to make sure all links are updated accordingly to send readers to correct desired locations

**Comment by AmandaLBaker** [comment]
Rough and Tumble Notes:
- [x] "The Rough and Tumble of Tech" Part 1, bottom bolded line that says "continued in part 2" should be a link, but doesn't go anywhere. There's an additional "link for this post" which is confusing since it's for Part 1, but can accidentally be read to mean link for the following part.
- [x] Rough and Tumble tags are inconsistent. Some are just "site-specific" and some are "site-specific-immersive theatre" as one long tag. Update all 4 parts to have the same 4 tags: Sébastien Heins, Torien Cafferata, immersive theatre, site-specific.
- [x] The formatting of the bottom sections of each part is inconsistent. Some have links to past parts, others don't. Part 4's looks the cleanest overall. Should prob update to make them consistent.

Part 1:
![Part 1](https://user-images.githubusercontent.com/22263358/114590372-b142d600-9c56-11eb-8c59-339a3cee5ced.png)
Part 2:
![Part 2](https://user-images.githubusercontent.com/22263358/114590435-c6b80000-9c56-11eb-9ed1-0e383b8a1dab.png)
Part 3:
![Part 3](https://user-images.githubusercontent.com/22263358/114590447-c91a5a00-9c56-11eb-8c43-e7b636fb7eea.png)
Part 4:
![Part 4](https://user-images.githubusercontent.com/22263358/114590455-cb7cb400-9c56-11eb-8e26-c2b7e66f5990.png)

**Comment by AmandaLBaker** [comment]
Rough and Tumble Notes continued:

- [x] Rough and Tumble Part 1, first "Overhear" link results in a get error: Cannot GET /blog/2020/11/08/exchange_part1/%5Bhttps://vimeo.com/273055640%5D
- [x] Rough and Tumble Part 3, "Myst-esque adventure game from 1997" is missing final bracket ")" in link name, results in a "did you mean?" wiki result
- [x] Not seeing any links throughout Part 4. Checking that this is the intent, not that links were missed.

**Comment by jakemoves** [comment]
Please verify the checked-off fixes above... haven't done the Rough and Tumble 'other parts' formatting just yet.

**Comment by AmandaLBaker** [comment]
Tag Notes:
- [x] "Calling the Shows" I think the tag "site-specific dance" could be separated into "site-specific" and "dance"
- [x] "Plays You Play" adding immersive theatre tag to it since it's a big thread 
- [x] "Plays You Play" also has an "Overhear" tag, if this is a used tag it should also be included on "Rough and Tumble Part 2" since it references Overhear heavily too [jake note: I just deleted the Overhear tag]

Link Notes:
- [x]  "Magic and The Afterparty" I think it would be worth adding a link in this blog post to The Afterparty page like the other post does that references it.
- [x]  On the "introduction" article, it reference the Confab. Is there documentation of this event elsewhere that would be worth linking to?

**Comment by jakemoves** [comment]
The Rough and Tumble 'cross-links' should now be: Parts 1, 2, and 3 link to the next part; Part 4 has links to 1, 2, and 3.

**Comment by AmandaLBaker** [comment]
Initial batch of fixes are verified and good to go, and the re-do of the Rough and Tumble end bits looks good.

**Comment by AmandaLBaker** [comment]
Tags are currently as follows in the posts:

An Introduction
	Tags: Cohort, blog, mobile

Plays You Play
	Tags: Overhear, Torien Cafferata, site-specific

Rough and Tumble Part 1
	Tags: Sebastien Heins, Torien Cafferata, immersive theatre, site-specific

Time and The Afterparty
	Tags: Jordan Campbell, The Afterparty, site-specific

Rough and Tumble Part 2
	Tags: Sebastien Heins, Torien Cafferata, immersive theatre, site-specific

Magic and The Afterparty
	Tags: Elizabeth Staples, The Afterparty, site-specific

Calling the Shows
	Tags: LOT X, Laura Cournoyea, site-specific dance

Kill Your Darlings
	Tags: BUS 1.2.3., Dominique Banoun, non-linear

Rough and Tumble Part 3
	Tags: Sebastien Heins, Torien Cafferata, immersive theatre, site-specific

Rough and Tumble Part 4
	Tags: Sebastien Heins, Torien Cafferata, immersive theatre, site-specific

As mentioned earlier, I think the "site-specific dance" tag in the Calling the Shows posts should be separated out into two tags. And then if there are other posts that warrant the "dance" tag, that would be good to add. Then food for thought is adding "theatre" as it's own tag for the theatre-centric posts (since "site-specific" doesn't specify dance/theatre etc).

Non-linear still feels a bit weird as a tag since no other posts use it, but since that is a descriptor in the post itself I guess it works. This one also does reference the company in the tag, but if we don't want to  do that in other posts that's fine (had talked about that earlier).

**Comment by jakemoves** [comment]
Ok, I think I've caught everything here.

There currently isn't anywhere to link to Confab stuff -- but I'm aiming to get those videos up, so please remind me to add it once they are :)

**Comment by AmandaLBaker** [comment]
Great, everything looks good from my end on the changes. I'll leave this open until the Confab links are added in.

**Comment by jakemoves** [comment]
Please close this and make a new issue for that...

**Comment by AmandaLBaker** [comment]
Cool! Sounds good.
