### ISSUE TITLE
🔵 Blog: add final posts

### ISSUE THREAD

**Issue by AmandaLBaker** [jakemoves/cohort-server#259]
Add final posts to the blog

**Comment by AmandaLBaker** [comment]
Two things:
1. The Rough and Tumble of Tech Parts 1, 2 and 3 don't have any images associated with them. Is this the intent? The rest of the posts have images, so just want to flag.
2. I see 4 new posts. If that is the correct amount, then this issue is good to close!

**Comment by jakemoves** [comment]
Yes, those posts don't have header images.
